
# Utiliza la imagen oficial de PostgreSQL desde el Docker Hub
FROM postgres:latest

#COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

# Variables de entorno para configurar PostgreSQL
ENV POSTGRES_USER=usuario
ENV POSTGRES_PASSWORD=contrasena
ENV POSTGRES_DB=globant

EXPOSE 5432

